const types = {
    FETCH_POSTS: "FETCH_POSTS",
    FETCH_SINGLE_POST: "FETCH_SINGLE_POST",
    FETCH_USERS: "FETCH_USERS",
    FETCH_SINGLE_USER: "FETCH_SINGLE_USER",
    CHANGE_SCREEN: "CHANGE_SCREEN",
    FETCH_USERS_POSTS: "FETCH_USERS_POSTS",
    FETCH_USER: "FETCH_USER",
    FETCH_USER_INFO: "FETCH_USER_INFO",
    FETCH_CURRENT_CLASSROOM: "FETCH_CURRENT_CLASSROOM",
    FETCH_COURSES: "FETCH_COURSES",
    FETCH_ANALYSIS: "FETCH_ANALYSIS",
    FETCH_ALL_USERS: "FETCH_ALL_USERS",
    FETCH_QUIZ: "FETCH_QUIZ"
    
}

export default types;